# Generated by Django 2.2.4 on 2020-07-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favbook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fav',
            field=models.ManyToManyField(null=True, related_name='favbook', to='favbook_app.User'),
        ),
    ]
